baseURL = "https://gorgew.github.io/"
languageCode = "en-us"
title = "George Wang"
theme = "anubis"

[params]
  sitename = "George Wang"
 
[[menu.main]]
name = "About"
url = "/"
weight = 1


[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[params.social]]
id= "github"
name= "gorgew"

[[params.social]]
id= "linkedin"
name= "g-s-wang"